### PR TITLE
Runaway

### PR DESCRIPTION
**Pull request by matthewr6**

### CODE REVIEW

**Comment by an-OK-squirrel** [comment]
OK, yay!

**Comment by matthewr6** [comment]
Could you merge it?  I can't figure out how :L

**Comment by matthewr6** [comment]
nvm.

don't forget to comment on your code :)  (i'm guilty of it too :P)

**Comment by an-OK-squirrel** [comment]
Lol, ok.

**Comment by an-OK-squirrel** [comment]
YUS THANKS

**Comment by an-OK-squirrel** [comment]
How did you do it? :p

**Comment by an-OK-squirrel** [comment]
It broke! D:

**Comment by matthewr6** [comment]
what broke?

**Comment by an-OK-squirrel** [comment]
lol, i was installing from master. Anyways, now "hide names" is broken and all the profane names D:

**Comment by matthewr6** [comment]
we can worry about that later

**Comment by an-OK-squirrel** [comment]
I'd like to know why thouh.

**Comment by matthewr6** [comment]
Works for me

**Comment by an-OK-squirrel** [comment]
Huh. D:

**Comment by matthewr6** [comment]
What is

``` javascript
tempMoveX = Math.min(tempMoveX, 7043);
tempMoveY = Math.min(tempMoveY, 7043);
tempMoveX = Math.max(tempMoveX, -7043);
tempMoveY = Math.max(tempMoveY, -7043);
```

for?

**Comment by an-OK-squirrel** [comment]
So it doesn't get stuck going out of bounds.

**Comment by an-OK-squirrel** [comment]
(I'll comment my code later :P)

**Comment by matthewr6** [comment]
Ok

**Comment by an-OK-squirrel** [comment]
You figured it out yet?

**Comment by matthewr6** [comment]
Working on it.

**Comment by an-OK-squirrel** [comment]
Figured out out! Also, should we delete runaway now?

**Comment by matthewr6** [comment]
Sure, but don't do anything for a few minutes because I'm working on something to make it seek food when there aren't any enemies

**Comment by an-OK-squirrel** [comment]
Ok! Also add comments for me :p

**Comment by matthewr6** [comment]
Will try

**Comment by an-OK-squirrel** [comment]
You never told me how you fixed the merge conflict

**Comment by an-OK-squirrel** [comment]
Taking a break, seeya

**Comment by matthewr6** [comment]
I don't know how I fixed it xD

**Pull request merged**
