### PR TITLE
Make global settings. No way to change settings, planning for the fut…

### PR DESCRIPTION
**Pull request by an-OK-squirrel**
…ure! But seriously. Wouldn't it be great to have a "settings" function?

### CODE REVIEW

**Comment by PullJosh** [comment]
Why is the "move away from edge" script removed?

**Comment by matthewr6** [comment]
Just merge it into globalsettings first

**Comment by an-OK-squirrel** [comment]
I must have not pulled before writing.

**Comment by an-OK-squirrel** [comment]
Won't it work if I auto-merge?

**Comment by PullJosh** [comment]
@Firedrake969 Move away from edge branch already deleted. :/ Maybe you could work your git magic?

**Comment by matthewr6** [comment]
edge-avoid?
done.

**Comment by PullJosh** [comment]
Doesn't seem to be done. The edge avoid script still isn't in `globalsettings`. Am I missing something?

**Comment by matthewr6** [comment]
I guess I can do it for you
You're sure it was the edge-avoid branch?

**Comment by PullJosh** [comment]
What other branch would help avoid edges? :P

**Comment by matthewr6** [comment]
Seems like the commit got overwritten

edit - yeah, @an-OK-squirrel overwrote it:
https://github.com/ScratchAgarioBots/agario-bot/commit/90efc5d4124797c75993829362a3d94f7a563265#diff-3deb4bbb2131417b70ba135e5a6f7715L863

**Comment by an-OK-squirrel** [comment]
_cries_

**Comment by an-OK-squirrel** [comment]
bump

**Comment by PullJosh** [comment]
What do you want me to do?

**Comment by an-OK-squirrel** [comment]
Wait, I got an idea...

**Comment by an-OK-squirrel** [comment]
Should work.

**Comment by an-OK-squirrel** [comment]
Can I merge myself now that avoid edges is back?

**Comment by matthewr6** [comment]
ok

**Comment by an-OK-squirrel** [comment]
Done

**Pull request merged**
