### PR TITLE
Feeding

### PR DESCRIPTION
**Pull request by matthewr6**
so we have a backup.  This works right now.

I've gotten over 100 seconds and 100 score with it, so I think it's worthy

### CODE REVIEW

**Comment by matthewr6** [comment]
@an-OK-squirrel 
not you though :P

**Comment by an-OK-squirrel** [comment]
What did I do this time?

**Comment by PullJosh** [comment]
You assigned me, but I don't know what I'm supposed to do. :P

**Comment by an-OK-squirrel** [comment]
Lol just push the merge button.

**Comment by PullJosh** [comment]
Hope I did that right. :P

**Comment by an-OK-squirrel** [comment]
You did for once. :P Also, I have an idea...

**Comment by PullJosh** [comment]
"For once" is pretty accurate. xD

**Comment by PullJosh** [comment]
The thing I'm best at is labeling issues. :P

**Comment by an-OK-squirrel** [comment]
Yep!

**Comment by PullJosh** [comment]
Shall I delete the "feeding" branch?

**Comment by an-OK-squirrel** [comment]
Keep it for now.

**Comment by PullJosh** [comment]
k

**Comment by an-OK-squirrel** [comment]
What now?

**Comment by PullJosh** [comment]
I'm going to go break stuff on my new branch.

**Comment by an-OK-squirrel** [comment]
I'm gonna take a long break.

**Pull request merged**
