### PR TITLE
Food clusters

### PR DESCRIPTION
**Pull request by matthewr6**
Try to get bot to ignore food inside other players' buffer zones.  Some polishing would be nice, especially from whoever wrote the buffer zone code.

### CODE REVIEW

**Comment by an-OK-squirrel** [comment]
Trying it...

**Comment by matthewr6** [comment]
Testing or polishing it up?

**Comment by Firedrake969** [comment]
Testing or polishing?

**Comment by PullJosh** [comment]
I can't figure out why it isn't very effective... It blocks some food, but not all.

It's quite strange.

**Comment by an-OK-squirrel** [comment]
Closing, cause it's broken as heck

**Pull request closed without merging**
